// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use pooler URL for queries, direct URL for migrations
    url: process.env["DATABASE_URL"]!,
    directUrl: process.env["DIRECT_URL"],
  } as { url: string; directUrl?: string },
});
